import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
   devopsSidebar: [
    {
      type: 'category',
      label: 'DevOps Learning Path',
      collapsed: false,
      items: [
        // These paths correspond to MDX files under docs/learning-paths/devops/
        'learning-paths/devops/01-intro',
        'learning-paths/devops/02-ci-cd',
        'learning-paths/devops/03-containers',
        'learning-paths/devops/04-monitoring',
      ],
    },
   ],
};

export default sidebars;
